version: '2.3'
services:
  db:
    image: postgres:latest
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: forge
      POSTGRES_PASSWORD: forge
  api:
    image: gleandroj/laravel:slim
    ports:
      - "8070:80"
    volumes:
      - .:/home/deploy/app:Z
    depends_on:
      - db
